### ISSUE TITLE
Add more styled examples

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/react-simple-card#15]
This is the current list of example we have at the moment. I've used [**codesandbox.io**](https://codesandbox.io) and suggest you do the same. 

- [**Basic layout**](https://codesandbox.io/s/611monz7qz) - `Card`, `CardHeader`, `CardBody`, `CardFooter` 
- [**Basic layout with Image header instead**](https://codesandbox.io/s/k2kwznw6qv) - `Card`, `ImageHeader`, `CardBody`, `CardFooter` 
- [**Without header**](https://codesandbox.io/s/zqk7jvrnym) - `Card`, `CardBody`, `CardFooter` 
- [**Body only**](https://codesandbox.io/s/vnlxr3l6j0) - `Card`, `CardBody`

If you are going to check the examples, you are going to find that there are no custom CSS styles overwrites. All examples have `react-simple-card` default component styles. This is absolutely okay because it shows everything we need in order to make the `Card` component to work. Unfortunately, it looks a bit cheap and not properly styled.

Obviously, I wanted to make it as plain as possible so devs could easily integrate it into their projects and add the stylings they wanted. 

So regards to the task if anyone is going to help, you can play around with styles and make different examples of the `Card` components, so anyone could take a ready-to-use solution. 

Finally, just submit a new PR and add your link to [`README.md`](https://github.com/ummahusla/react-simple-card/blob/master/README.md#examples)

**Comment by OsamaJandali** [comment]
Can you give more description for this?

**Comment by ummahusla** [comment]
@OsamaJandali Done, thanks! 👍

**Comment by OsamaJandali** [comment]
Well thanks, I will give it a shot.

**Comment by jcrawford** [comment]
I agree with this, a good example of how to add styles would be good.  I cannot seem to figure out how to get the styles passed into the CardHeader since it requires an object I have tried ```style={font-size: 22px, font-weight: bold}``` but this does not work and just throws errors.

**Comment by ummahusla** [comment]
@jcrawford Right, Right.

The first step is to create an object

```
{ 
    fontSize: 22,
    fontWeight: 'bold'
}
```

Secondly, pass it to `style` prop

```
<CardHeader style={{fontSize: 22, fontWeight: 'bold'}}>
	Phasellus eleifend orci sed neque ultricies viverra
</CardHeader>
```

Working demo

https://codesandbox.io/s/819wwr6joj


Looking forward your PRs!
