### ISSUE TITLE
Improve code coverage to 100% 

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/react-simple-card#33]

**Comment by taksuparth** [comment]
@ummahusla I would love to pick this up

**Comment by ummahusla** [comment]
Coverage increased (+15.9%) to 94.118%


---


@taksuparth Feel free to send the PR mate.

**Comment by ldanet** [comment]
I misread the thread and I thought that @taksuparth had submitted a PR that got merged.
Sorry for stealing your PR 😞
